# version: '3.9'
services:
  redis:
    image: redis
    container_name: redis
    #restart: unless-stopped
    volumes:
      - ./redis/data:/data
    networks:
      - net-db
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    #restart: unless-stopped
    networks:
      - net-db
    ports:
      - 9084:8001
    volumes:
      - ./redisinsight/db:/db

networks:
  net-db:
    name: net-db
    external: true
    driver: bridge