# version: '3'
services:
  postgres16:
    image: postgres
    #restart: unless-stopped
    container_name: postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - net-db
    ports:
      - 5432:5432

networks:
  net-db:
    name: net-db
    external: true
    driver: bridge